//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SAM
{
    using System;
    using System.Collections.Generic;
    
    public partial class Catalog
    {
        public int id { get; set; }
        public string Name { get; set; }
        public string Price { get; set; }
    
        public virtual Agent Agent { get; set; }
        public virtual Delivery Delivery { get; set; }
        public virtual Store Store { get; set; }
    }
}
