//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SAM
{
    using System;
    using System.Collections.Generic;
    
    public partial class Client
    {
        public string Phone { get; set; }
        public string Email { get; set; }
        public int id { get; set; }
    
        public virtual Demand Demand { get; set; }
        public virtual Personal Personal { get; set; }
        public virtual Supply Supply { get; set; }
    }
}
