//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SAM
{
    using System;
    using System.Collections.Generic;
    
    public partial class Store
    {
        public int id { get; set; }
        public string Catalog { get; set; }
        public string Price { get; set; }
    
        public virtual Catalog Catalog1 { get; set; }
        public virtual Delivery Delivery { get; set; }
        public virtual Demand Demand { get; set; }
        public virtual Personal Personal { get; set; }
    }
}
